name: Rust

on:
  push:
    branches: [ "*.*.*/main" ]
  pull_request:
    branches: [ "*.*.*/main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      run: cd mafia-client
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build_server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      run: cd mafia-server
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
